export interface BreedInfo {
  name: string; // 견종명
  code: string; // 견종 코드
  color: string; // 대표 색상 (Hex)
  weightRange: string; // 평균 몸무게 (kg)
  size: string; // 크기 분류
  personality: string; // 견종별 성격
  geneticDiseases: string[]; // 유의해야 할 유전병
  recommendedExercise: string; // 추천 운동량
}

export const BREED_DATA: BreedInfo[] = [
  // --- 소형견 ---
  {
    name: "말티즈",
    code: "101",
    color: "#FFFFFF",
    weightRange: "2.0 ~ 4.0",
    size: "소형견",
    personality: "활발하고 애교가 많으며 보호자에게 강한 애착을 보입니다.",
    geneticDiseases: ["슬개골 탈구", "유류증(눈물자국)", "기관지 협착증"],
    recommendedExercise: "하루 30분 내외의 가벼운 산책",
  },
  {
    name: "푸들",
    code: "102",
    color: "#A0522D",
    weightRange: "3.0 ~ 6.0",
    size: "소형견",
    personality: "매우 똑똑하고 훈련성능이 뛰어나며 활동적입니다.",
    geneticDiseases: ["슬개골 탈구", "진행성 망막 위축증", "외이염"],
    recommendedExercise: "하루 30분 ~ 1시간",
  },
  {
    name: "포메라니안",
    code: "103",
    color: "#D2691E",
    weightRange: "1.5 ~ 3.5",
    size: "소형견",
    personality: "호기심이 많고 당차며, 경계심과 애교를 동시에 지녔습니다.",
    geneticDiseases: ["슬개골 탈구", "기관지 협착증", "알로페시아(탈모)"],
    recommendedExercise: "하루 20분 ~ 30분 가벼운 걷기",
  },
  {
    name: "치와와",
    code: "104",
    color: "#F5DEB3",
    weightRange: "1.5 ~ 3.0",
    size: "소형견",
    personality: "독립심과 충성심이 강하고 겁이 없으며 경계심이 많습니다.",
    geneticDiseases: ["슬개골 탈구", "수두증", "기관지 협착증"],
    recommendedExercise: "하루 15분 ~ 30분",
  },
  {
    name: "시츄",
    code: "105",
    color: "#DEB887",
    weightRange: "4.0 ~ 7.5",
    size: "소형견",
    personality: "매우 온순하고 사람을 좋아하며 느긋한 편입니다.",
    geneticDiseases: ["안구 질환(각막염 등)", "호흡기 질환", "피부염"],
    recommendedExercise: "하루 30분 (더위에 취약하여 여름 주의)",
  },
  {
    name: "요크셔테리어",
    code: "106",
    color: "#708090",
    weightRange: "2.0 ~ 3.2",
    size: "소형견",
    personality: "똑똑하고 자신감이 넘치며 보호자에 대한 충성도가 높습니다.",
    geneticDiseases: ["기관지 협착증", "슬개골 탈구", "치주 질환"],
    recommendedExercise: "하루 30분 내외",
  },
  {
    name: "비숑 프리제",
    code: "107",
    color: "#FFFFFF",
    weightRange: "3.0 ~ 6.0",
    size: "소형견",
    personality: "명랑하고 사교성이 매우 좋으며 에너지가 넘칩니다.",
    geneticDiseases: ["슬개골 탈구", "백내장", "알레르기 피부염"],
    recommendedExercise: "하루 40분 ~ 1시간",
  },
  {
    name: "닥스훈트",
    code: "108",
    color: "#8B4513",
    weightRange: "4.0 ~ 9.0",
    size: "소형견",
    personality: "용감하고 호기심이 많으며 사냥개 특유의 활동성이 있습니다.",
    geneticDiseases: ["추간판 탈출증(디스크)", "비만"],
    recommendedExercise: "하루 40분 ~ 1시간 (무리한 점프/계단 지양)",
  },
  {
    name: "미니어처 슈나우저",
    code: "109",
    color: "#808080",
    weightRange: "5.0 ~ 8.0",
    size: "소형견",
    personality: "경계심이 강하여 집을 잘 지키고, 똑똑하고 활동적입니다.",
    geneticDiseases: ["요로결석", "췌장염", "백내장"],
    recommendedExercise: "하루 40분 ~ 1시간 이상",
  },
  {
    name: "말티푸",
    code: "110",
    color: "#F5DEB3",
    weightRange: "2.5 ~ 5.0",
    size: "소형견",
    personality: "다정하고 장난기가 많으며 친화력이 좋습니다.",
    geneticDiseases: [
      "슬개골 탈구",
      "유류증",
      "위험률은 비교적 낮음 (믹스견 이점)",
    ],
    recommendedExercise: "하루 30분 ~ 40분",
  },

  // --- 중형견 ---
  {
    name: "웰시코기",
    code: "201",
    color: "#CD853F",
    weightRange: "10.0 ~ 14.0",
    size: "중형견",
    personality:
      "활달하고 스킨십을 좋아하며 소몰이 습성으로 활동량이 많습니다.",
    geneticDiseases: ["추간판 탈출증(디스크)", "고관절 이형성증", "비만"],
    recommendedExercise: "하루 1 ~ 2시간 (비만 관리 필수)",
  },
  {
    name: "비글",
    code: "202",
    color: "#8B4513",
    weightRange: "9.0 ~ 11.0",
    size: "중형견",
    personality: "에너지가 넘치고 낙천적이며 고집이 있는 편입니다.",
    geneticDiseases: ["외이염", "비만", "간질"],
    recommendedExercise: "하루 1 ~ 2시간 충분한 후각 활동",
  },
  {
    name: "시바견",
    code: "203",
    color: "#DAA520",
    weightRange: "8.0 ~ 11.0",
    size: "중형견",
    personality: "독립적이고 청결함을 유지하려 하며 경계심이 있습니다.",
    geneticDiseases: ["알레르기 피부염", "슬개골 탈구", "녹내장"],
    recommendedExercise: "하루 1시간 이상",
  },
  {
    name: "보더콜리",
    code: "204",
    color: "#000000",
    weightRange: "14.0 ~ 20.0",
    size: "중형견",
    personality: "지능이 매우 높고 일하는 것을 좋아하며 활동량이 최상급입니다.",
    geneticDiseases: ["고관절 이형성증", "콜리 안구 기형(CEA)", "뇌전증"],
    recommendedExercise: "하루 2시간 이상의 고강도 산책 및 훈련",
  },
  {
    name: "프렌치 불독",
    code: "205",
    color: "#000000",
    weightRange: "8.0 ~ 13.0",
    size: "중형견",
    personality: "온순하고 애정이 많으며 헛짖음이 적은 편입니다.",
    geneticDiseases: ["단두종 호흡기 증후군", "피부 알레르기", "척추 질환"],
    recommendedExercise: "하루 30분 (더운 날씨에 열사병 각별히 주의)",
  },
  {
    name: "코카 스파니엘",
    code: "206",
    color: "#D2B48C",
    weightRange: "10.0 ~ 15.0",
    size: "중형견",
    personality: "사람을 매우 좋아하고 다정하며 에너지가 넘칩니다.",
    geneticDiseases: ["외이염", "진행성 망막 위축증", "지루성 피부염"],
    recommendedExercise: "하루 1시간 이상 활기찬 산책",
  },
  {
    name: "진돗개",
    code: "207",
    color: "#FFFFF0",
    weightRange: "15.0 ~ 23.0",
    size: "중형견",
    personality: "주인에 대한 충성심과 복종심이 매우 강하고 독립적입니다.",
    geneticDiseases: ["위장관 질환", "피부 알레르기"],
    recommendedExercise: "하루 1.5 ~ 2시간",
  },
  {
    name: "스피츠",
    code: "208",
    color: "#FFFFFF",
    weightRange: "6.0 ~ 10.0",
    size: "중형견",
    personality: "경계심이 강해 짖음이 있을 수 있으며 쾌활하고 영리합니다.",
    geneticDiseases: ["슬개골 탈구", "유류증"],
    recommendedExercise: "하루 40분 ~ 1시간",
  },

  // --- 대형견 ---
  {
    name: "골든 리트리버",
    code: "301",
    color: "#F0E68C",
    weightRange: "25.0 ~ 34.0",
    size: "대형견",
    personality: "매우 온화하고 인내심이 강하며 친화력이 뛰어납니다.",
    geneticDiseases: [
      "고관절 이형성증",
      "종양(혈관육종 등)",
      "알레르기성 피부염",
    ],
    recommendedExercise: "하루 1 ~ 2시간",
  },
  {
    name: "래브라도 리트리버",
    code: "302",
    color: "#F5F5DC",
    weightRange: "25.0 ~ 36.0",
    size: "대형견",
    personality: "성격이 밝고 활동적이며, 영리하고 사람을 잘 따릅니다.",
    geneticDiseases: ["고관절 이형성증", "비만", "백내장"],
    recommendedExercise: "하루 1.5 ~ 2시간",
  },
  {
    name: "사모예드",
    code: "303",
    color: "#FFFFFF",
    weightRange: "16.0 ~ 30.0",
    size: "대형견",
    personality: "친근하고 장난기가 많으며 경계심이 적어 사교적입니다.",
    geneticDiseases: ["고관절 이형성증", "진행성 망막 위축증", "당뇨병"],
    recommendedExercise: "하루 1.5 ~ 2시간 (더위 취약)",
  },
  {
    name: "시베리안 허스키",
    code: "304",
    color: "#A9A9A9",
    weightRange: "16.0 ~ 27.0",
    size: "대형견",
    personality: "독립적이면서도 고집이 세고 에너지가 폭발적입니다.",
    geneticDiseases: ["백내장", "고관절 이형성증", "피부 피부증"],
    recommendedExercise: "하루 1.5 ~ 2시간 이상 달리기 혹은 빠른 걷기",
  },
  {
    name: "저먼 셰퍼드",
    code: "305",
    color: "#553518",
    weightRange: "30.0 ~ 40.0",
    size: "대형견",
    personality: "충성심이 극도로 강하고 영리하며 보호본능이 뛰어납니다.",
    geneticDiseases: ["고관절 이형성증", "위염전(위꼬임)", "퇴행성 척수염"],
    recommendedExercise: "하루 2시간 이상 높은 활동량 및 훈련 요소 포함",
  },
  {
    name: "로트와일러",
    code: "306",
    color: "#000000",
    weightRange: "35.0 ~ 60.0",
    size: "대형견",
    personality:
      "가족에 대한 애정이 깊고 조용하지만 낯선 이에겐 강한 보호본능을 보입니다.",
    geneticDiseases: ["고관절 이형성증", "심장 질환(대동맥하협착증)", "골육종"],
    recommendedExercise: "하루 1.5 ~ 2시간 집중적인 훈련과 운동",
  },
  {
    name: "올드 잉글리쉬 쉽독",
    code: "307",
    color: "#D3D3D3",
    weightRange: "27.0 ~ 45.0",
    size: "대형견",
    personality: "다정하고 애교가 많으며 어린이들과 잘 어울립니다.",
    geneticDiseases: ["고관절 이형성증", "백내장", "갑상선 기능 저하증"],
    recommendedExercise: "하루 1 ~ 2시간",
  },

  // --- 기타 ---
  {
    name: "기타 (믹스견 등)",
    code: "000",
    color: "#D3D3D3",
    weightRange: "0.0 ~ 0.0",
    size: "기타",
    personality: "개체별로 매우 다양하게 나타납니다.",
    geneticDiseases: ["유전병 위험이 순종보다 비교적 낮고 개체별 상이함"],
    recommendedExercise:
      "개체의 체격 및 에너지 수준에 맞춰 탄력적으로 조절 (일반적으로 1시간 내외)",
  },
];
